name: ai_connect
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.16
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  lottie: ^3.3.0
  go_router: ^14.6.2
  google_sign_in: ^6.2.2
  icons_launcher: ^3.0.0
  image_picker: ^1.1.2
  internet_connection_checker_plus: ^2.5.2
  intl: ^0.19.0
  objectbox: ^4.0.3
  objectbox_flutter_libs: ^4.0.3
  path_provider: ^2.1.5
  provider: ^6.1.2
  supabase_flutter: ^2.8.1
  country_code_picker: ^3.1.0
  pinput: ^5.0.0
  google_generative_ai: ^0.4.6

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  objectbox_generator: ^4.0.3

#dependency_overrides:
#  file_picker:
#    git:
#      url: https://github.com/abdelaziz-mahdy/flutter_file_picker
#      ref: fix-flutter-3.27-compile-error

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/json/
    - assets/images/
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: ChakraPetch
      fonts:
        - asset: assets/fonts/ChakraPetch.ttf
    - family: IndieFlower
      fonts:
        - asset: assets/fonts/IndieFlower.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf
    - family: SourGummy
      fonts:
        - asset: assets/fonts/SourGummy.ttf
    - family: Teko
      fonts:
        - asset: assets/fonts/Teko.ttf

flutter_native_splash:
  color: "#24252A"
  image: assets/images/splash_logo.png
  android: true
  ios: true
  android_gravity: fill
  android_12:
    color: "#24252A"
    image: assets/images/splash_logo.png

icons_launcher:
  image_path: "assets/images/ai.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
